version: '3.3'
services:
  app:
    build: .
    command: rails s -b 0.0.0.0
    volumes:
      - .:/usr/src
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      REDIS_URL: redis://redis:6379/0

  service_http:
    image: webs3
    ports:
      - "3001:5678"

  report_serv:
    image: res48

    ports:
      - "3002:5679"

  db:
    image: postgres:11.5
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres:/var/lib/postgresql/data



  sidekiq:
    build: .
    command: sidekiq
    volumes:
      - .:/usr/src
    depends_on:
      - db
      - rabbitmq
      - redis
    environment:
      REDIS_URL: redis://redis:6379/0
    tmpfs:
      - /usr/src/tmp/pids

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "15672:15672"
    volumes:
      - rabbit:/var/lib/rabbitmq

  redis:
    image: redis:5-alpine
    volumes:
      - redis:/data

volumes:
  postgres:
  redis:
  rabbit:


